# Generated by Django 5.1 on 2024-08-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pase', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corto', models.CharField(max_length=255)),
                ('pase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacion.pase')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAleatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=10, unique=True)),
                ('pase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='votacion.pase')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacion', models.IntegerField(default=0)),
                ('corto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='votacion.corto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='votacion.usuarioaleatorio')),
            ],
        ),
    ]
