# Generated by Django 5.1.1 on 2024-10-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0002_votacion_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pase',
            name='orden',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
