# Generated by Django 5.1.1 on 2024-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0003_pase_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
