# Generated by Django 5.1.1 on 2024-10-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0004_alter_corto_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votacion',
            constraint=models.UniqueConstraint(fields=('corto', 'usuario'), name='unique_corto_usuario'),
        ),
    ]
