# Generated by Django 5.1.1 on 2024-10-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0005_votacion_unique_corto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='corto',
            name='orden',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
